---
all:
  children:
    incus_hosts:
      hosts:
        redactum:
          ansible_host: "{{ lookup('ansible.builtin.env', 'INCUS_HOST_IP') }}"
          ansible_user: "{{ lookup('ansible.builtin.env', 'INCUS_HOST_USER') | default('pythas', true) }}"
          ansible_connection: ssh

    arr_containers:
      hosts:
        caddy:
          ansible_connection: community.general.incus
          ansible_incus_remote: redactum
          ansible_user: root

        notificurom:
          ansible_connection: community.general.incus
          ansible_incus_remote: redactum
          ansible_user: root
